---
title: "Client Report - Project 1"
subtitle: "Course DS 250"
author: "Dale McBride"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


## Elevator pitch

_After analyzing the data some interesting insights developed. Some key insights were that each name has a specific trend that corrosponds with it. The trends seen with names can be related to events that happen. Such as a movie that has been released recently._

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://raw.githubusercontent.com/byuidatascience/data4names/master/data-raw/names_year/names_year.csv")
```

## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

_My name usage throughout the years has changed significantly as it nears my birth month. In 1958 is where the name peaked in usage and after that it dropped off significantly. When I was born in 2002 I was only one out of four hundred and ten named Dale that year._

```{python}
#| label: Q1 chart
#| code-summary: plot example
#| fig-cap: ""
#| fig-align: center
# Include and execute your code here
chart = px.line(df.query('name == "Dale"'),
    x="year", 
    y="Total",
    title = "Usage of the name Dale"
)
chart.add_annotation(x=1958, y=5735, text="Peak in name usgage 1958", font=dict(size=10), arrowcolor="black")

chart.add_annotation(x=2002, y=410, text="My Birth Year 2002", font=dict(size=10), arrowcolor="black")

chart.show()
```

## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_If I were to guess the age of someone Brittany I would guess the age 34. 1990 is when the most children were named Brittany. Making the age of 34 to be the best option. Ages I would not guess would be 45 or 14 because there are very few children named Brittany at those age points. _

```{python}
#| label: Q2 chart
#| code-summary: plot example
#| fig-cap: ""
#| fig-align: center
# Include and execute your code here
chart = px.line(df.query('name == "Brittany"'),
    x="year", 
    y="Total",
    title = "Brittany name usage",
    
)
chart.add_annotation(x=1990, y=32562, text="1990", font=dict(size=10), arrowcolor="black")



chart.show()
```

## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?__

_From 1920-1960 the name Mary was used a ton compared to the other names. They all collectively have a rise in usage at about 1950. After the year 1950 they all start to diwndle in there usage._

```{python}
#| label: Q3 chart
#| code-summary: plot example
#| fig-cap: ""
#| fig-align: center
# Include and execute your code here
chart = px.line(df.query('name == ["Mary", "Martha", "Peter", "Paul"]'),
    x="year", 
    y="Total",
    color = 'name',
    title = 'Name Usage'
    
)

chart.show()
```

## QUESTION|TASK 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__

_Taking a famous name such as Luke from Star Wars we can see that an increase begins to happen in the name usage after the year 1977. 1977 happens to be the same year that the movie for Star Wars came out. Leading me to beleive that there is a corrolation between the two._

```{python}
#| label: Q4 chart
#| code-summary: plot example
#| fig-cap: ""
#| fig-align: center
# Include and execute your code here
chart = px.bar(df.query('name == "Luke"'),
    x="year", 
    y="Total",
    title = 'Amount of children being named Luke'
)
chart.add_annotation(x=1977, y=1250, text="1977", font=dict(size=14), arrowcolor="black")

chart.show()
```
