---
layout: cv
title: Dale McBride's CV
---
# Dale McBride
Computer Science, Life Learner.

<div id="webaddress">
<a href="dalemcbride@gmail.com">dalemcbride@gmail.com</a>
| <a href="https://github.com/DaleMcBride21/my_portfolio">My Github page</a>
</div>


## Currently

A Student at BYUI

### Specialized in

Currently Studying Computer Science and Minoring in Business Management


### Research interests




## Education

`2023-now`
__Computer Science Degree__

`2023 - now`
__Business Minor__

`2017-2021`
__High School Diploma__

-



## Awards

`Honor Society`

I met the academic requirements to be apart of the Honor Society



## Publications

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->

### Journals

`1669`
Newton Sir I, De analysi per æquationes numero terminorum infinitas. 

`1669`
Lectiones opticæ.

etc. etc. etc.

### Patents

`2012`
Infinitesimal calculus for solutions to physics problems, [SMBC](http://www.techdirt.com/articles/20121011/09312820678/if-patents-had-been-around-time-newton.shtml) patent 001


## Occupation

`July 2023 - August 2023`
__Philpott Farm and Sawmill__, Otto, WY

- Farm Hand
- I managed and took care of farm land and other tasks that were given to me.

`June 2020 - August 2020`
__Meeteetse School__, Meeteetse, WY

- Mainenance Worker
- I maintained or cleaned the different systems and facilities that were on the campus.


<!-- ### Footer

Last updated: May 2013 -->